repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
      - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.4
  hooks:
      - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0  # Use the ref you want to point at
  hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch', 'main']
      - id: pretty-format-json
        args: ['--autofix']
      - id: requirements-txt-fixer